services:
  redis:
    image: redis:7-alpine
    container_name: bnpl-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    restart: unless-stopped
    expose:
      - '3000'
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis_data:
